import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

async function render() {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);

  return worker.fetch(
    new Request("http://localhost/", { headers: { accept: "text/html", host: "localhost" } }),
    { ASSETS: { fetch: async () => new Response("Not found", { status: 404 }) } },
    { waitUntil() {}, passThroughOnException() {} },
  );
}

test("server-renders the complete advertising strategy", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  assert.match(response.headers.get("content-type") ?? "", /^text\/html\b/i);

  const html = await response.text();
  assert.match(html, /<title>广告行业 AI 素材生产方案｜BytePlus<\/title>/);
  assert.match(html, /把素材生产/);
  assert.match(html, /2026 VIDEO API TAM/);
  assert.match(html, /2026 IMAGE API TAM/);
  assert.match(html, /\$150K/);
  assert.match(html, /海外数字视频广告市场 TAM 拆解/);
  assert.match(html, /增长不在总盘/);
  assert.match(html, /品牌与效果各占一半/);
  assert.match(html, /真正的 TAM/);
  assert.doesNotMatch(html, /market-structure-2026\.jpg/);
  assert.doesNotMatch(html, /video-budget-2021-2030\.jpg/);
  assert.doesNotMatch(html, /video-production-tam\.jpg/);
  assert.match(html, /2026 MARKET STRUCTURE/);
  assert.match(html, /\$640–680B/);
  assert.match(html, /剔除中国市场/);
  assert.match(html, /剔除海外传统线下媒体/);
  assert.match(html, /纯搜索广告/);
  assert.match(html, /纯数字视频广告/);
  assert.match(html, /静态社交与展示/);
  assert.match(html, /零售媒体静态广告/);
  assert.match(html, /Google · Bing/);
  assert.match(html, /Amazon · Walmart/);
  assert.match(html, /VIDEO AD BUDGET/);
  assert.match(html, /2030 VALUE CAPTURE/);
  assert.doesNotMatch(html, /MARKET FUNNEL/);
  assert.doesNotMatch(html, /从广告预算，切到模型 API/);
  assert.doesNotMatch(html, /网页原生表达|网页原生重绘|网页以文字门槛呈现|不嵌入原图|platformNote|SOURCE ·|REFERENCE PAGE|localhost:4173|rev\./);
  assert.match(html, /三大细分赛道全景对比/);
  assert.match(html, /Social Video/);
  assert.match(html, /Netflix \/ Disney\+/);
  assert.match(html, /YouTube 长视频/);
  assert.match(html, /1,150亿/);
  assert.match(html, /450 → 900/);
  assert.match(html, /品牌 80%/);
  assert.match(html, /15%–20%/);
  assert.match(html, /长尾稳增 · AI 搜索分流/);
  assert.match(html, /2\. 主流视频广告/);
  assert.match(html, /场景和需求分析/);
  assert.match(html, /先看典型样片/);
  assert.match(html, /典型客户画像/);
  assert.match(html, /展开具体制作流程/);
  assert.equal((html.match(/class="sampleCase /g) ?? []).length, 3);
  assert.equal((html.match(/class="caseTile"/g) ?? []).length, 3);
  assert.equal((html.match(/<video /g) ?? []).length, 2);
  assert.match(html, /brand-reference\.mp4/);
  assert.match(html, /performance-generated\.mp4/);
  assert.match(html, /确定性来自流程设计/);
  assert.match(html, /一次过率决定综合成本/);
  assert.match(html, /Display Ads，是独立生产线/);
  assert.match(html, /作为独立的第三类广告生产线/);
  assert.match(html, /SOCIAL STATIC/);
  assert.match(html, /3:1 BANNER/);
  assert.equal((html.match(/class="workflowDisclosure"/g) ?? []).length, 3);
  assert.equal((html.match(/class="workflowDisclosure requirementDisclosure"/g) ?? []).length, 3);
  assert.doesNotMatch(html, /<details class="workflowDisclosure(?: requirementDisclosure)?" open/);
  assert.match(html, /Campaign Agent/);
  assert.doesNotMatch(html, /THE GROWTH LOOP|ROAS 反馈回流/);
  assert.doesNotMatch(html, /PERFORMANCE DEEP DIVE|scene-perf|每条可投放素材的综合成本|ANNUAL SUPPLY|STANDARD FORMAT|VARIANTS \/ SKU|AI PENETRATION|costFormula|perfKpis|darkTable/);
  assert.match(html, /3\. 客群策略/);
  assert.match(html, /钱从哪里来，收入在哪里放大/);
  assert.equal((html.match(/class="customerStory /g) ?? []).length, 3);
  assert.equal((html.match(/class="customerRouteNode /g) ?? []).length, 3);
  assert.match(html, /AI PRODUCT/);
  assert.match(html, /BUSINESS TEAM/);
  assert.match(html, /Campaign Agent · 1 → 3/i);
  assert.match(html, /素材自动化成为 Agent 标配/);
  assert.match(html, /投放规模/);
  assert.match(html, /AI 素材占比/);
  assert.match(html, /Pinterest/);
  assert.match(html, /2\.5 之后/);
  assert.doesNotMatch(html, /codex-preview|SkeletonPreview|Your site is taking shape/);
});

test("covers every Bojie requirement in the page source", async () => {
  const page = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");

  assert.match(page, /\$160B/);
  assert.match(page, /\$260B/);
  assert.match(page, /\$0\.4B/);
  assert.match(page, /\$1\.25M/);
  assert.match(page, /约 \$450M ARR/);
  assert.match(page, /\$150K/);
  assert.match(page, /5\.6%/);
  assert.match(page, /13%/);
  assert.match(page, /620 → 1,150/);
  assert.match(page, /\+100%/);
  assert.match(page, /消耗极快 · 成本高/);
  assert.match(page, /有线电视数字化归入/);
  assert.doesNotMatch(page, /样片需求|WHAT MUST BE TRUE|caseNeeds|needs: \[/);
  assert.doesNotMatch(page, /SOURCE ·|REFERENCE PAGE|localhost:4173|rev\. 8900|关键数字为方向性估算|待孙越交叉验证|参考页估算/);
  assert.match(page, /按样片拆解/);
  assert.match(page, /Shein · Temu/);
  assert.match(page, /Smartly\.io · Creatopy/);
  assert.match(page, /WPP · Havas · Publicis/);
  assert.match(page, /展开具体制作流程/);
  assert.match(page, /制作方/);
  assert.match(page, /VIDEO \/ IMAGE MODEL REQUIREMENTS/);
  assert.match(page, /CTV 和流媒体大屏广告/);
  assert.match(page, /Roku、Netflix、Disney、Prime/);
  assert.match(page, /应用内广告网络和激励视频/);
  assert.match(page, /AppLovin AXON、Unity Ads/);
  assert.match(page, /程序化展示广告网络/);
  assert.match(page, /The Trade Desk、InMobi/);
  assert.equal((page.match(/\/media\/demo-/g) ?? []).length, 3);
  assert.equal((page.match(/type: "video"/g) ?? []).length, 2);
  assert.match(page, /\/media\/brand-reference\.mp4/);
  assert.match(page, /\/media\/performance-generated\.mp4/);
  assert.match(page, /layout: "display"/);
  assert.match(page, /曝光量与品牌知名度/);
  assert.match(page, /tCPA：目标转化成本/);
  assert.match(page, /Retargeting 兜底/);
  assert.match(page, /15 \/ 30 秒标准格式/);
  assert.match(page, /10–15 秒最常见/);
  assert.match(page, /300×250、728×90、160×600/);
  assert.match(page, /AI 模型 Workflow 逐渐代替实拍和渲染/);
  assert.match(page, /Ad Campaign Agent 引入广告素材自动化制作/);
  assert.match(page, /Ad Campaign Agent 引入图片素材自动化编辑/);
  assert.match(page, /C2PA 水印/);
  assert.match(page, /美分级、秒级出图/);
  assert.match(page, /nano banana 2 为主/);
  assert.match(page, /WPP/);
  assert.match(page, /Havas/);
  assert.match(page, /AppLovin/);
  assert.match(page, /钛动/);
  assert.match(page, /L’Oréal/);
  assert.match(page, /Coca-Cola/);
  assert.match(page, /Pinterest/);
  assert.match(page, /Reddit/);
  assert.match(page, /\$6M MRR/);
  assert.match(page, /\$1\.5M MRR/);
  assert.match(page, /约 \$16\.67M \/ 月/);
  assert.match(page, /头部客户参考 · 约 \$1M MRR/);
  assert.match(page, /\$2–5B \/ 年/);
  assert.match(page, /50–100 万张图片 \/ 月/);
  assert.match(page, /50 个品牌、150 个市场/);
  assert.match(page, /WPP Open 约 60%/);
  assert.match(page, /ToB 转售约 40%/);
  assert.match(page, /80K\+ EMPLOYEES/);
  assert.match(page, /\$11B\+ 年化广告 Spend/);
  assert.match(page, /实拍生命周期约 3–4 个月/);
  assert.match(page, /growthEngine: \["投放规模", "AI 素材占比", "单素材模型消耗", "模型收入"\]/);
  assert.doesNotMatch(page, /2027–28/);
  assert.match(page, /算法 \/ AI 产品团队/);
  assert.match(page, /AI 产品/);
  assert.match(page, /Display Automation/);
  assert.match(page, /nano banana 2/);
  assert.equal((page.match(/no: "0[1-4]"/g) ?? []).length, 4);
  assert.match(page, /物理语义/);
  assert.match(page, /品牌资产的硬约束/);
  assert.match(page, /专业音频可交付/);
  assert.match(page, /精准编辑/);
  assert.match(page, /视频素材生产支出/);
  assert.match(page, /\$25–30B/);
  assert.match(page, /\$12\.8B/);
  assert.match(page, /10–100/);
  assert.match(page, /Meta Reels/);
  assert.equal((page.match(/className="marketPillar /g) ?? []).length, 4);
  assert.match(page, /33%/);
  assert.match(page, /26%/);
  assert.match(page, /24%/);
  assert.match(page, /17%/);
  assert.match(page, /\$220B/);
  assert.match(page, /\$110B/);
  assert.match(page, /网站 Banner/);
  const conclusion02Index = page.indexOf("CONCLUSION 02");
  const segmentOverviewIndex = page.indexOf('className="segmentComparison marketSegmentOverview"');
  const conclusion03Index = page.indexOf("CONCLUSION 03");
  assert.ok(conclusion02Index >= 0 && conclusion02Index < segmentOverviewIndex);
  assert.ok(segmentOverviewIndex < conclusion03Index);
  assert.equal((page.match(/tamCaptureVisual/g) ?? []).length, 1);
  assert.doesNotMatch(page, /tamFormula/);
  assert.doesNotMatch(page, /const marketFunnel/);
  assert.doesNotMatch(page, /shell marketFunnel/);
  assert.doesNotMatch(page, /agentSection|agentCopy|agentSignals|agentSignal|className="loop"|loopStep|loopReturn/);
  assert.match(page, /<span>03<\/span> \/ CUSTOMER STRATEGY/);
  assert.match(page, /<span>04<\/span> \/ SOLUTION FOCUS/);
  assert.match(page, /<span>05<\/span> \/ ROADMAP/);
});

test("keeps responsive safeguards for desktop, tablet, phone, and narrow phone", async () => {
  const css = await readFile(new URL("../app/globals.css", import.meta.url), "utf8");

  assert.match(css, /@media \(min-width: 1440px\)/);
  assert.match(css, /@media \(min-width: 1600px\) \{/);
  assert.match(css, /@media \(min-width: 1600px\) and \(min-height: 980px\)/);
  assert.match(css, /@media \(min-width: 1101px\)/);
  assert.match(css, /calc\(100svh - 76px\)/);
  assert.match(css, /@media \(max-width: 1100px\)/);
  assert.match(css, /@media \(max-width: 900px\)/);
  assert.match(css, /@media \(max-width: 760px\)/);
  assert.match(css, /@media \(max-width: 600px\)/);
  assert.match(css, /@media \(max-width: 380px\)/);
  assert.match(css, /overflow-x: clip/);
  assert.match(css, /@media \(hover: none\)/);
  assert.match(css, /\.customerRoute \{ display: grid; grid-template-columns: repeat\(3, 1fr\)/);
  assert.match(css, /\.customerArchitecture \{ display: grid; grid-template-columns: \.86fr 1\.14fr/);
  assert.match(css, /\.revenueEquation \{ display: grid; grid-template-columns: repeat\(4, 1fr\)/);
  assert.match(css, /\.gapGrid \{ grid-template-columns: repeat\(4, 1fr\)/);
  assert.match(css, /\.solutionStack \{ display: grid; grid-template-columns: repeat\(3, 1fr\)/);
  assert.match(css, /\.segmentCell strong \{[^}]*font-size: 16px/);
  assert.match(css, /\.segmentCell span \{[^}]*font-size: 12px/);
  assert.match(css, /\.dimensionCell b \{ font-size: 14px/);
  assert.match(css, /\.sampleMedia > video \{[^}]*object-fit: cover/);
  assert.match(css, /\.displayBoard \{ grid-template-columns: 1fr/);

  const page = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  assert.match(page, /className="heroFlow"/);
  assert.match(page, /生产[\s\S]*测试[\s\S]*放大/);
});
