import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

async function render() {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);

  return worker.fetch(
    new Request("http://localhost/", { headers: { accept: "text/html", host: "localhost" } }),
    { ASSETS: { fetch: async () => new Response("Not found", { status: 404 }) } },
    { waitUntil() {}, passThroughOnException() {} },
  );
}

test("server-renders the complete advertising strategy", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  assert.match(response.headers.get("content-type") ?? "", /^text\/html\b/i);

  const html = await response.text();
  const sceneOverviewHtml = html.slice(html.indexOf('class="sceneLandscapePage"'), html.indexOf('class="sceneDemoPages"'));
  const sceneDemoHtml = html.slice(html.indexOf('class="sceneDemoPages"'), html.indexOf('class="customerFlowPage"'));
  const performanceSolutionHtml = html.slice(html.indexOf('class="solutionPage performanceSolutionPage"'), html.indexOf('class="solutionPage displaySolutionPage"'));
  const displaySolutionHtml = html.slice(html.indexOf('class="solutionPage displaySolutionPage"'), html.indexOf('class="playableSolution"'));
  assert.match(html, /<title>BytePlus 广告行业素材生产方案<\/title>/);
  assert.match(html, /class="coverPage"/);
  assert.match(html, /<main class="siteRoot" id="top">/);
  assert.match(html, /网页文字编辑器/);
  assert.match(html, /编辑文字/);
  assert.doesNotMatch(html, /class="coverPage" id="top"/);
  assert.match(html, /视频成为主流/);
  assert.match(html, /AI 生产走向规模化/);
  assert.match(html, /Video goes mainstream/);
  assert.match(html, /AI production scales/);
  assert.match(html, /ADS Creative Solution/);
  assert.doesNotMatch(html, /素材生产变成增长引擎|BYPASS advertising industry|ADS × AI|2026 GPM/);
  assert.doesNotMatch(html, /coverSubtitle/);
  assert.match(html, /视频广告/);
  assert.match(html, /第一大类型/);
  assert.match(html, /BUDGET FLOW/);
  assert.match(html, /海外数字广告市场规模与增速/);
  assert.doesNotMatch(html, /未来 3–4 年 · 广告预算结构性迁移|近万亿美元总盘|2026 四大支柱 → 2030 视频广告 #1/);
  assert.match(html, /CTR \/ CVR/);
  assert.match(html, /AI 降低视频生产成本/);
  assert.match(html, /供给规模化/);
  assert.match(html, /预算迁移/);
  assert.match(html, /VALUE CAPTURE/);
  assert.match(html, /MODEL API/);
  assert.match(html, /中.{1,8}EN/);
  assert.doesNotMatch(html, /2026 BUSINESS TARGET|视频模型目标 DRR|2026 目标与|MONTHLY DR RAMP|REGIONAL MIX|头部客户保底合同|JUL · BASE|DEC · STABLE/);
  assert.doesNotMatch(html, /market-structure-2026\.jpg/);
  assert.doesNotMatch(html, /video-budget-2021-2030\.jpg/);
  assert.doesNotMatch(html, /video-production-tam\.jpg/);
  assert.match(html, /2026 · CURRENT MARKET/);
  assert.match(html, /\$640–680B/);
  assert.match(html, /剔除中国约 \$160B 与海外线下约 \$200B/);
  assert.match(html, /SEARCH/);
  assert.match(html, /VIDEO/);
  assert.match(html, /DISPLAY/);
  assert.match(html, /RMN/);
  assert.match(html, /2030 TOTAL VIDEO BUDGET/);
  assert.match(html, /\$25–30B/);
  assert.match(html, /\$1B/);
  assert.match(html, /\$2B/);
  assert.match(html, /\$6\.4B/);
  assert.match(html, /\$12\.8B/);
  assert.doesNotMatch(html, /MARKET FUNNEL/);
  assert.doesNotMatch(html, /从广告预算，切到模型 API/);
  assert.doesNotMatch(html, /网页原生表达|网页原生重绘|网页以文字门槛呈现|不嵌入原图|platformNote|SOURCE ·|REFERENCE PAGE|localhost:4173|rev\./);
  assert.doesNotMatch(html, /三大细分赛道全景对比/);
  assert.match(html, /查看三赛道/);
  assert.doesNotMatch(html, /FASTEST-GROWING FORMAT|CAUSAL ENGINE|只使用已知视频预测/);
  assert.doesNotMatch(html, /四类大盘口径中的 Video/);
  assert.match(html, /AI 使制作成本下降，视频供给规模化/);
  assert.match(html, /2021–23 \+44%/);
  assert.match(html, /2023–26 \+63%/);
  assert.match(html, /2026–30 \+79%/);
  assert.match(html, /class="flowOutcomeDefault"/);
  assert.match(html, /class="mobileOutcomeSummary"/);
  assert.match(html, /class="mobileSegmentDetails"/);
  assert.doesNotMatch(html, /增长率仅在点击后强调|避免默认信息过载/);
  assert.match(html, /SOCIAL VIDEO/);
  assert.match(html, /CTV/);
  assert.match(html, /OLV/);
  assert.match(html, /62 → 115B/);
  assert.match(html, /45 → 90B/);
  assert.match(html, /38 → 55B/);
  assert.equal((html.match(/class="flowBaseline flow/g) ?? []).length, 4);
  assert.equal((html.match(/class="marketFlowSvg"/g) ?? []).length, 1);
  assert.match(html, /SCENE LANDSCAPE/);
  assert.match(html, /2\. 主流广告场景/);
  assert.match(html, /和需求分析/);
  assert.doesNotMatch(sceneOverviewHtml, /VIDEO MODEL API · 2026|IMAGE MODEL API · 2026|视频 API 规模|图片模型 API 规模|主流模型/);
  assert.equal((html.match(/class="sceneLandscapeCard /g) ?? []).length, 3);
  assert.match(html, /头部 5 家代理商.*WPP · Havas · Publicis · Dentsu · Omnicom.*次头部代理商.*Brandtech（Pencil）· 博报堂/s);
  assert.match(html, /AdTech 公司.*AppLovin · 钛动.*广告主（品牌方）.*欧莱雅 · 可口可乐等.*Paid Media.*Pinterest · Reddit · LinkedIn Ads 等/s);
  assert.match(html, /AdTech \/ 创意自动化平台.*AppLovin · Smartly\.io · Creatopy.*零售媒体和 Paid Media.*Criteo · Pinterest.*代理商.*WPP · Havas · Publicis · Dentsu · Omnicom/s);
  assert.doesNotMatch(sceneOverviewHtml, /Shein|Temu|Amazon 卖家|Shopify 商家/);
  assert.equal((html.match(/<video /g) ?? []).length, 20);
  assert.equal((html.match(/class="sceneDemoPage sceneDemoPage/g) ?? []).length, 3);
  assert.match(html, /scene-brand-demo/);
  assert.match(html, /scene-performance-demo/);
  assert.match(html, /scene-display-demo/);
  assert.match(html, /REFERENCE DEMO/);
  assert.match(html, /src="\/media\/brand-reference\.mp4"/);
  assert.match(html, /src="\/media\/performance-generated\.mp4"/);
  assert.match(html, /poster="\/media\/performance-poster\.jpg"/);
  assert.match(html, /AI 生成效果广告样片/);
  assert.match(html, /一次过率决定综合成本/);
  assert.doesNotMatch(sceneDemoHtml, /performance-reference\.mp4|performance-reference\.jpg/);
  assert.doesNotMatch(sceneDemoHtml, /WHO MAKES IT|制作方 \/ 客户|sceneDemoWho/);
  assert.equal((sceneDemoHtml.match(/class="sceneDemoDisclosure" open=""/g) ?? []).length, 9);
  assert.doesNotMatch(sceneDemoHtml, /样片 → 制作流程 → 模型需求 → 竞品模型|05 STEPS|04 STEPS/);
  assert.equal((sceneDemoHtml.match(/VIDEO \+ IMAGE/g) ?? []).length, 1);
  assert.doesNotMatch(sceneDemoHtml, /sceneProductionDisclosure|sceneProductionBody/);
  assert.equal((sceneDemoHtml.match(/class="sceneDemoStage"/g) ?? []).length, 3);
  assert.match(sceneDemoHtml, /sceneDemoStage.*sceneDemoVisual.*sceneDemoBrief.*sceneDemoExpanders/s);
  assert.match(sceneDemoHtml, /具体制作流程/);
  assert.match(sceneDemoHtml, /AI 模型 Workflow 逐渐代替实拍和渲染/);
  assert.match(sceneDemoHtml, /Ad Campaign Agent 引入广告素材自动化制作/);
  assert.match(sceneDemoHtml, /Ad Campaign Agent 引入图片素材自动化编辑/);
  assert.match(sceneDemoHtml, /图片模型.*生成分镜故事板、概念图、关键视觉 KV/s);
  assert.match(sceneDemoHtml, /图片模型.*商品白底图转场景图、虚拟模特和数字人形象定型/s);
  assert.match(sceneDemoHtml, /市场主流模型（竞对）/);
  assert.match(sceneDemoHtml, /Veo 3\.1 · Runway/);
  assert.match(sceneDemoHtml, /Kling 3\.0（商品展示 \/ 口播性价比）· Veo 3\.1/);
  assert.match(sceneDemoHtml, /nano banana 2 为主/);
  assert.ok(
    html.indexOf('class="sceneDemoPages"') < html.indexOf('id="solution-focus"'),
    "场景样片拆解必须先于、且独立于后续方案展示",
  );
  assert.match(html, /Campaign Agent/);
  assert.equal((html.match(/class="solutionPage brandSolutionPage"/g) ?? []).length, 1);
  assert.equal((html.match(/class="solutionPage /g) ?? []).length, 3);
  assert.match(html, /品牌广告制作方案/);
  assert.match(html, /Brand Advertising Production Solution/);
  assert.match(html, /src="\/media\/sofa\/final-film\.mp4"/);
  assert.doesNotMatch(html, /One packshot in|A whole catalog/);
  assert.match(html, /CG 锁定控制，AI 完成输出/);
  assert.match(html, /输入资产/);
  assert.match(html, /AI 理解 \+ 数字孪生/);
  assert.match(html, /CG 控制 · Blender/);
  assert.match(html, /图像渲染/);
  assert.match(html, /最终输出 · KV \+ 视频/);
  assert.match(html, /SEEDREAM 5\.0 PRO/i);
  assert.match(html, /\/media\/sofa\/kv-wide\.jpg/);
  assert.ok(
    html.indexOf('class="brandSofaPanel"') < html.indexOf('class="brandArchitecturePanel"') &&
      html.indexOf('class="brandArchitecturePanel"') < html.indexOf('class="brandDemoStrip"'),
    "单页品牌方案必须按 Sofa 成片、架构、四个既有样片排序",
  );
  assert.doesNotMatch(html, /品牌广告，.*怎么进入专业制作|一个模型底座，.*三条生产管线/s);
  assert.equal((html.match(/class="brandDemoCompactCard"/g) ?? []).length, 4);
  assert.equal((html.match(/class="brandProofDisclosure"/g) ?? []).length, 0);
  assert.match(html, /Branding Ads 样片/);
  assert.match(html, /Vision LLM · Seed 2\.1/);
  assert.match(html, /Seedream 5\.0 Pro/);
  assert.match(html, /夜景光影与运动表现/);
  assert.match(html, /Branding Ads demos/);
  assert.match(html, /Portrait detail &amp; lash-level texture/);
  assert.match(html, /CMF materials &amp; product macro/);
  assert.match(html, /HOSPITALITY \/ LIFESTYLE/);
  assert.equal((html.match(/class="performanceEvidenceCard"/g) ?? []).length, 4);
  assert.equal((html.match(/class="performanceProofDisclosure"/g) ?? []).length, 4);
  assert.match(html, /商品展示.*UGC 实拍感.*商品开箱与人物交互.*试穿试戴试妆带货/s);
  assert.match(html, /热点洞察.*Seed.*广告脚本.*Seed.*爆款复刻.*爆款复刻 Agent/s);
  assert.doesNotMatch(html, /class="brandSolutionScope"|10–15s · 9:16/);
  assert.match(html, /效果广告制作方案/);
  assert.match(html, /流程、样片与能力证据/);
  assert.match(html, /5 STEPS/);
  assert.match(html, /热点洞察.*广告脚本.*AI 内容生产.*投放测试.*爆款复刻/s);
  assert.equal((html.match(/class="performanceFlowSummary"/g) ?? []).length, 5);
  assert.match(html, />Seed<.*>Seed<.*Seedream \+ Seedance.*Campaign Agent.*爆款复刻 Agent/s);
  assert.match(html, /跑赢素材回到洞察，持续迭代/);
  assert.doesNotMatch(performanceSolutionHtml, /客户在做|我们提供|FIVE-STEP OPERATING LOOP|03 SHOTS|展开模型能力证据/);
  assert.match(html, /只改变目标效果，不破坏人物身份/);
  assert.match(html, /Display Ads 制作方法/);
  assert.match(html, /一个母版，规模化交付/);
  assert.match(html, /id="solution-display-demos"/);
  assert.equal((html.match(/class="solutionPage displaySolutionPage"/g) ?? []).length, 1);
  assert.doesNotMatch(html, /class="solutionPage displayDemoPage"/);
  assert.match(displaySolutionHtml, /一个 Brief，变成 Creative Matrix.*从母版到多规格交付/s);
  assert.match(displaySolutionHtml, /Campaign Brief.*Brand Kit.*Product Feed.*Creative Planner.*CREATIVE SPEC.*Seedream.*APPROVED MASTER.*Template \+ DCO.*VARIANT FACTORY.*QA Gate.*ASSET HUB \/ API/s);
  assert.match(displaySolutionHtml, /MODEL.*视觉创意.*SYSTEM.*确定性生产.*Creative Planner.*CTR.*CVR.*CPA/s);
  assert.doesNotMatch(displaySolutionHtml, /用图片样片|CAPABILITY PROOF|MODEL BOUNDARY/);
  assert.match(html, /displayDemoSquare.*Retail Media.*displayDemoLandscape.*16:9.*displayDemoBanner.*3:1/s);
  assert.equal((html.match(/class="displayLightbox"/g) ?? []).length, 3);
  assert.match(html, /点击图片放大/);
  assert.match(html, /查看关键帧/);
  assert.match(html, /商品几何、材质与承重关系贯穿使用过程/);
  assert.match(html, /Campaign Brief/);
  assert.match(html, /Creative Planner/);
  assert.match(html, /APPROVED MASTER/);
  assert.match(html, /QA Gate/);
  assert.match(html, /Template \+ DCO/);
  assert.match(html, /尺寸 × 语言 × SKU × 人群/);
  assert.match(html, /id="solution-playable"/);
  assert.match(html, /一个游戏素材.*市场调研.*创意策划.*自动生产.*可投放广告包/s);
  assert.match(html, /Hook × 视觉 × CTA/);
  assert.match(html, /AI 自动编排 · 全流程无需人工/);
  assert.equal((html.match(/class="playableDemoCard"/g) ?? []).length, 2);
  assert.match(html, /CakeSort.*TinyFishing/s);
  assert.match(html, /cake-sort\.html.*tiny-fishing\.html/s);
  assert.doesNotMatch(html, /4 类玩法测试|2 类通过/);
  assert.match(html, /playable\.byteplus-demo\.com/);
  assert.doesNotMatch(html, /THE GROWTH LOOP|ROAS 反馈回流/);
  assert.doesNotMatch(html, /PERFORMANCE DEEP DIVE|id="scene-perf"|每条可投放素材的综合成本|ANNUAL SUPPLY|STANDARD FORMAT|VARIANTS \/ SKU|costFormula|perfKpis|darkTable/);
  assert.match(html, /客群策略/);
  assert.match(html, /钱从上往下走/);
  assert.match(html, /价值在中间放大/);
  assert.match(html, /品牌主.*代理商.*AdTech \/ MarTech.*Paid Media/s);
  assert.doesNotMatch(html, /当前模型 API 钱包口径|钱包口径待补充/);
  assert.match(html, /定义预算与品牌资产/);
  assert.match(html, /承接创意与制作预算/);
  assert.match(html, /把投放预算转成持续生产/);
  assert.match(html, /完成分发并返回效果信号/);
  assert.match(html, /L’Oréal · CreateAI/);
  assert.match(html, /WPP · Havas/);
  assert.match(html, /Criteo · Pinterest/);
  assert.equal((html.match(/class="lorealCasePage"/g) ?? []).length, 1);
  assert.equal((html.match(/class="wppCasePage wppPresentationPage"/g) ?? []).length, 1);
  assert.equal((html.match(/class="adtechCasePage"/g) ?? []).length, 1);
  assert.equal((html.match(/class="customerStory /g) ?? []).length, 0);
  assert.match(html, /欧莱雅客户拆解.*先进入.*CreTech.*再随市场放大/s);
  assert.match(html, /50.*内部创意实验.*50.*外部发布素材/s);
  assert.match(html, /50–100.*万张.*10–20.*万条/s);
  assert.doesNotMatch(html, /\$5B|≈ \$0\.5B|年度消耗暂无可核口径|待客户确认/);
  assert.match(html, /50.*BRANDS.*150.*MARKETS/s);
  assert.match(html, /模型 API.*CreTech 白名单/s);
  assert.doesNotMatch(html, /预算如何变成模型消耗|L’ORÉAL · CUSTOMER BREAKDOWN|API FIRST · WORKFLOW SECOND|P0 模型 API · P1 工作流|企业级 SLA \+ generation credit/);
  assert.match(html, /WPP · 从代理商切入.*Previs.*Cutdown.*Localization/s);
  assert.doesNotMatch(html, /CORE JUDGEMENT|不要卖孤立工具/);
  assert.match(html, /外部商用输出.*一年前.*36%.*最近一季度.*55%/s);
  assert.match(html, /lorealReportCanvas.*lorealReportCore.*lorealReportEngine.*lorealReportStrategy/s);
  const wppHtml = html.slice(html.indexOf('class="wppCasePage wppPresentationPage"'), html.indexOf('class="adtechCasePage"'));
  assert.match(wppHtml, /WPP \/ HAVAS.*代理商是最大的增长入口.*从简单的AI创意预览.*真正投产到Production/s);
  assert.match(wppHtml, /模型 API 为主/);
  assert.match(wppHtml, /WPP Open.*覆盖WPP 80,000\+ 员工/s);
  assert.doesNotMatch(wppHtml, /01 · 短期 · 2026|02 · 中长期|03 · 当前/);
  assert.equal((wppHtml.match(/class="wppWorkstreamIdentity wppStage/g) ?? []).length, 3);
  assert.match(wppHtml, /CREATIVE.*30%.*70%.*概念、分镜与 Pre-vis.*速度.*风格控制.*品牌资产/s);
  assert.match(wppHtml, /PRODUCTION.*10% 至 15%.*70%.*3D \/ Digital Twin.*一致性.*可控镜头.*4K.*3D渲染/s);
  assert.match(wppHtml, /MEDIA.*20% 至 30%.*Master Video.*渠道、市场、语言与人群.*精准编辑.*本地化/s);
  assert.doesNotMatch(wppHtml, /商业结果|Time-and-Materials|Outcome-based|更高毛利/);
  assert.doesNotMatch(wppHtml, /wppMigrationRail|wppMoneyRoute|wppValueLadder|wppBusinessTeams|wppEntryRail/);
  assert.doesNotMatch(wppHtml, /≈ \$0\.2B/);
  assert.doesNotMatch(html, /\$6M MRR|\$5\.5M|\$0\.3–0\.5M|WPP Open 内部自用|ToB 对外转售/);
  assert.equal((html.match(/class="customerFlowStage /g) ?? []).length, 4);
  assert.match(html, /抓住 Campaign Agent 的增长窗口/);
  assert.match(html, /让素材自动化成为必要组成/);
  assert.match(html, /一条链路，带动持续收入放大/);
  assert.match(html, /AppLovin/);
  assert.match(html, /钛动/);
  const adtechHtml = html.slice(html.indexOf('class="adtechCasePage"'), html.indexOf('id="solution-focus"'));
  assert.match(adtechHtml, /MARKET STAGE.*1 → 3.*Campaign Agent.*进入可复制阶段.*素材自动化.*嵌入主链路.*AI 视频素材.*占比持续上升.*模型调用与收入.*同步放大/s);
  assert.match(adtechHtml, /Lumos \/ Navos/);
  assert.doesNotMatch(adtechHtml, /adtechReplicableStage|adtechGrowthLogic|adtechWalletBanner|adtechCaseFooter/);
  assert.doesNotMatch(adtechHtml, /≈ \$0\.2B|钱包深度|MRR|ARR|待确认|暂无可核/);
  assert.match(sceneDemoHtml, /scene-brand-demo.*brand-reference\.mp4/s);
  assert.match(sceneDemoHtml, /scene-performance-demo.*performance-generated\.mp4/s);
  assert.match(sceneDemoHtml, /scene-display-demo.*demo-display-commerce\.jpg/s);
  assert.doesNotMatch(sceneDemoHtml, /solution-focus|BRAND PRODUCTION|PERFORMANCE ADS/);
  assert.doesNotMatch(sceneDemoHtml, /MODEL LANDSCAPE/);
  assert.match(html, /规模化推广素材自动化，成为每个 Campaign Agent 的标配/);
  assert.match(html, /AI 制作占比/);
  assert.match(html, /FINAL · SEEDANCE REQUIREMENTS/);
  assert.doesNotMatch(html, /FINAL<\/span> \/ PRODUCT REQUIREMENTS|最终产品需求：|走向规模生产/);
  assert.doesNotMatch(html, /美国市场占比|REGION PRIORITY|Resell 政策|COMMERCIAL REQUIREMENT|渠道激励|规模返点/);
  assert.match(html, /id="product-requirements"/);
  assert.match(html, /模型短期能力短板/);
  assert.equal((html.match(/class="productGateCard productGateCard/g) ?? []).length, 4);
  assert.match(html, /3D 白模只能渲染，不能理解/);
  assert.match(html, /世界知识与物理常识缺失/);
  assert.match(html, /商品与品牌要素保真不足/);
  assert.match(html, /音频参考与情感仍不可控/);
  assert.doesNotMatch(html, /视觉渲染.*可规模生产|必须同时通过 4 \/ 4 门槛/s);
  assert.doesNotMatch(html, /codex-preview|SkeletonPreview|Your site is taking shape/);
});

test("covers every Bojie requirement in the page source", async () => {
  const page = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  const editor = await readFile(new URL("../app/InlineTextEditor.tsx", import.meta.url), "utf8");
  const sceneOverviewSource = page.slice(page.indexOf('id="scenarios"'), page.indexOf('className="sceneDemoPages"'));
  const sceneDemoSource = page.slice(page.indexOf('className="sceneDemoPages"'), page.indexOf('className="customerFlowPage"'));

  const coverIndex = page.indexOf('className="coverPage"');
  const marketHeroIndex = page.indexOf('className="marketHero marketFlowPage"');
  const scenarioPageIndex = page.indexOf('id="scenarios"');
  assert.ok(coverIndex >= 0 && coverIndex < marketHeroIndex);
  assert.ok(marketHeroIndex < scenarioPageIndex);
  assert.doesNotMatch(page, /className="targetPage"|id="targets"|2026 BUSINESS TARGET/);
  assert.equal((page.match(/className="coverPage"/g) ?? []).length, 1);
  assert.match(editor, /导出修改清单/);
  assert.match(editor, /对应 XPath/);
  assert.match(editor, /byteplus-ads-copy-changes\.json/);
  assert.doesNotMatch(editor, /导出 HTML|byteplus-ads-edited\.html/);
  assert.match(page, /视频成为主流，/);
  assert.match(page, /AI 生产走向规模化。/);
  assert.doesNotMatch(page, /素材生产变成增长引擎|BYPASS advertising industry|ADS × AI|2026 GPM/);
  assert.match(page, /\$145B/);
  assert.match(page, /\$160B/);
  assert.match(page, /\$260B/);
  assert.doesNotMatch(page, /约 \$450M ARR/);
  assert.match(page, /AI 降低视频生产成本/);
  assert.match(page, /供给规模化/);
  assert.match(page, /海外数字广告市场规模与增速/);
  assert.match(page, /VALUE CAPTURE/);
  assert.match(page, /\$2B/);
  assert.match(page, /62 → 115B/);
  assert.match(page, /\+100%/);
  assert.match(page, /38 → 55B/);
  assert.match(page, /2030 TOTAL VIDEO BUDGET/);
  assert.doesNotMatch(page, /样片需求|WHAT MUST BE TRUE|caseNeeds|needs: \[/);
  assert.doesNotMatch(page, /SOURCE ·|REFERENCE PAGE|localhost:4173|rev\. 8900|关键数字为方向性估算|待孙越交叉验证|参考页估算/);
  assert.match(page, /sceneLandscapePage/);
  assert.doesNotMatch(sceneOverviewSource, /sceneScaleRail|VIDEO MODEL API · 2026|IMAGE MODEL API · 2026|视频 API 规模|图片模型 API 规模|主流模型/);
  assert.match(page, /Smartly\.io · Creatopy/);
  assert.match(page, /零售媒体和 Paid Media.*Criteo · Pinterest/s);
  assert.doesNotMatch(page, /Amazon Ads · Walmart Connect/);
  assert.doesNotMatch(page, /Shein|Temu|Amazon 卖家|Shopify 商家/);
  assert.match(page, /AppLovin · Smartly\.io · Creatopy/);
  assert.match(page, /AdTech \/ 创意自动化平台/);
  assert.match(page, /代理商.*WPP · Havas · Publicis · Dentsu · Omnicom/s);
  assert.match(page, /WPP · Havas · Publicis/);
  assert.doesNotMatch(sceneDemoSource, /制作方 \/ 客户|sceneDemoWho/);
  assert.equal((sceneDemoSource.match(/className="sceneDemoDisclosure" open/g) ?? []).length, 3);
  assert.match(page, /曝光量 · 品牌知名度.*长期品牌心智/s);
  assert.match(page, /tCPA \/ tROAS.*CTR \/ CVR · CPI/s);
  assert.match(page, /CPM \/ CPC.*低成本覆盖 \+ 直接转化/s);
  assert.match(page, /CTV 和流媒体大屏广告/);
  assert.match(page, /Roku、Netflix、Disney、Prime/);
  assert.match(page, /应用内广告网络和激励视频/);
  assert.match(page, /AppLovin AXON、Unity Ads/);
  assert.match(page, /程序化展示广告网络/);
  assert.match(page, /The Trade Desk、InMobi/);
  assert.equal((page.match(/\/media\/demo-/g) ?? []).length, 9);
  assert.equal((page.match(/type: "video"/g) ?? []).length, 2);
  assert.match(page, /\/media\/brand-reference\.mp4/);
  assert.match(page, /\/media\/performance-generated\.mp4/);
  assert.match(page, /\/media\/performance-poster\.jpg/);
  assert.doesNotMatch(sceneDemoSource, /performance-reference\.mp4|performance-reference\.jpg/);
  assert.match(page, /layout: "display"/);
  assert.match(page, /曝光量与品牌知名度/);
  assert.match(page, /tCPA：目标转化成本/);
  assert.match(page, /Retargeting 兜底/);
  assert.match(page, /15 \/ 30 秒标准格式/);
  assert.match(page, /10–15 秒最常见/);
  assert.match(page, /300×250、728×90、160×600/);
  assert.match(page, /AI 模型 Workflow 逐渐代替实拍和渲染/);
  assert.match(page, /Ad Campaign Agent 引入广告素材自动化制作/);
  assert.match(page, /Ad Campaign Agent 引入图片素材自动化编辑/);
  assert.match(page, /C2PA 水印/);
  assert.match(page, /美分级、秒级出图/);
  assert.match(page, /nano banana 2 为主/);
  assert.match(page, /WPP/);
  assert.match(page, /Havas/);
  assert.match(page, /AppLovin/);
  assert.match(page, /钛动/);
  assert.match(page, /L’Oréal/);
  assert.match(page, /Coca-Cola/);
  assert.match(page, /Pinterest/);
  assert.match(page, /Reddit/);
  assert.doesNotMatch(page, /\$6M MRR|\$1\.5M MRR|约 \$16\.67M \/ 月|头部客户参考 · 约 \$1M MRR|\$2–5B \/ 年|WPP Open 约 60%|ToB 转售约 40%|\$11B\+ 年化广告 Spend/);
  assert.doesNotMatch(page, /2027–28/);
  assert.match(page, /Template \+ DCO/);
  assert.match(page, /nano banana 2/);
  assert.equal((page.match(/no: "0[1-4]"/g) ?? []).length, 4);
  assert.match(page, /3D 白模只能渲染，不能理解/);
  assert.match(page, /世界知识与物理常识缺失/);
  assert.match(page, /商品与品牌要素保真不足/);
  assert.match(page, /音频参考与情感仍不可控/);
  assert.match(page, /涂口红、穿衣等商品操作姿势错误/);
  assert.match(page, /Logo 与商标细节错误/);
  assert.match(page, /ElevenLabs 音频 × Seedance 视频对齐/);
  assert.match(page, /O3I3dWdKKof2DtxNkrolaGtIgzc/);
  assert.match(page, /视频广告制作总成本/);
  assert.match(page, /\$25–30B/);
  assert.match(page, /\$12\.8B/);
  assert.match(page, /10–100/);
  assert.match(page, /Meta Reels/);
  assert.equal((page.match(/className="flowBaseline flow/g) ?? []).length, 4);
  assert.match(page, /className="marketFlowSvg"/);
  assert.match(page, /\$220B/);
  assert.match(page, /\$110B/);
  const scenarioIndex = page.indexOf('id="scenarios"');
  assert.ok(marketHeroIndex >= 0 && marketHeroIndex < scenarioIndex);
  assert.equal((page.match(/className="segmentControl"/g) ?? []).length, 1);
  assert.doesNotMatch(page, /CONCLUSION 01|CONCLUSION 02|CONCLUSION 03/);
  assert.doesNotMatch(page, /tamCaptureVisual/);
  assert.doesNotMatch(page, /tamFormula/);
  assert.doesNotMatch(page, /const marketFunnel/);
  assert.doesNotMatch(page, /shell marketFunnel/);
  assert.doesNotMatch(page, /agentSection|agentCopy|agentSignals|agentSignal|className="loop"|loopStep|loopReturn/);
  assert.match(page, /customerFlowCanvas/);
  assert.equal((page.match(/role: "(预算源头|制作放大|复利消耗|媒体反馈)"/g) ?? []).length, 4);
  assert.match(page, /brandSolutionPage/);
  assert.match(page, /brandSofaPanel/);
  assert.match(page, /brandOriginalArchitecture/);
  assert.match(page, /Vision LLM · Seed 2\.1/);
  assert.match(page, /3D model · Seed3D 2\.0/);
  assert.match(page, /Production-ready videos/);
  assert.match(page, /brandDemoCompactGrid/);
  assert.match(page, /input-texture\.jpg/);
  assert.match(page, /digital-twin-poster\.png/);
  assert.match(page, /lighting-1\.jpg/);
  assert.match(page, /kv-ultrawide\.jpg/);
  assert.match(page, /performanceProductionFlow/);
  assert.match(page, /performanceEvidenceGallery/);
  assert.match(page, /performanceProofDisclosure/);
  assert.equal((page.match(/brand-[a-z]+-demo\.mp4/g) ?? []).length, 4);
  assert.equal((page.match(/performance-[a-z]+-demo\.mp4/g) ?? []).length, 4);
  assert.match(page, /displayArchitectureFocus/);
  assert.match(page, /displayDemoGallery/);
  assert.match(page, /display-lightbox-commerce.*display-lightbox-beauty.*display-lightbox-diwali/s);
  assert.match(page, /一个游戏素材/);
  assert.match(page, /输出合规可投的 Playable 包/);
  assert.match(page, /className="roadmapPage"/);
  assert.match(page, /从单点模型.*走向广告制作引擎/s);
  assert.match(page, /10–15%/);
  assert.match(page, /70%/);
  assert.match(page, /SINGLE MODEL → OMNI ENGINE/);
  assert.match(page, /创意意图.*空间与物理.*品牌资产.*编辑反馈/s);
  assert.match(page, /VALUE CAPTURE/);
  assert.match(page, /≈ 20%/);
});

test("keeps responsive safeguards for desktop, tablet, phone, and narrow phone", async () => {
  const css = await readFile(new URL("../app/globals.css", import.meta.url), "utf8");

  assert.match(css, /@media \(min-width: 1440px\)/);
  assert.match(css, /@media \(min-width: 1600px\) \{/);
  assert.match(css, /@media \(min-width: 1600px\) and \(min-height: 980px\)/);
  assert.match(css, /@media \(min-width: 1101px\)/);
  assert.match(css, /calc\(100svh - 76px\)/);
  assert.match(css, /@media \(max-width: 1100px\)/);
  assert.match(css, /@media \(max-width: 900px\)/);
  assert.match(css, /@media \(max-width: 760px\)/);
  assert.match(css, /@media \(max-width: 600px\)/);
  assert.match(css, /@media \(max-width: 380px\)/);
  assert.match(css, /overflow-x: clip/);
  assert.match(css, /@media \(hover: none\)/);
  assert.match(css, /\.customerFlowPage \{ height: 860px/);
  assert.match(css, /\.customerFlowCanvas \{[^}]*grid-template-columns: minmax\(0, 1fr\)/);
  assert.match(css, /\.customerFlowStage \{[^}]*grid-template-columns: 150px minmax\(190px, 1fr\) minmax\(205px, 1fr\) 155px/);
  assert.match(css, /@media \(max-width: 700px\) \{[\s\S]*?\.customerFlowStage \{[^}]*grid-template-columns: 1fr 1fr/);
  assert.match(css, /@media \(max-width: 1120px\) \{[\s\S]*?\.adtechCasePage/);
  assert.match(css, /@media \(max-width: 760px\) \{[\s\S]*?\.adtechAgentFlow \{ grid-template-columns: 1fr/);
  assert.match(css, /@media \(max-width: 760px\) \{[\s\S]*?\.adtechCustomerCards \{ grid-template-rows: auto auto/);
  assert.match(css, /@media \(max-width: 760px\) \{[\s\S]*?\.lorealBudgetSystem,[\s\S]*?\.lorealOrgSystem \{ grid-template-rows: auto auto auto; \}/);
  assert.match(css, /@media \(max-width: 760px\) \{[\s\S]*?\.wppWalletSystem,[\s\S]*?\.wppProductionSystem \{ grid-template-rows: auto auto auto auto; \}/);
  assert.match(css, /@media \(max-width: 760px\) \{[\s\S]*?\.adtechAgentSystem,[\s\S]*?\.adtechCustomerSystem \{ grid-template-rows: auto auto auto; \}/);
  assert.match(css, /@media \(max-width: 700px\) \{[\s\S]*?\.sceneDemoImages \{ height: auto; grid-template-rows: 62px auto 72px; \}/);
  assert.doesNotMatch(css, /\.adtechStory \{[^}]*background-color: var\(--ink\)/);
  assert.match(css, /\.adtechStory \{[^}]*background-color: #f6f7ef/);
  assert.match(css, /\.customerArchitecture \{ display: grid; grid-template-columns: \.86fr 1\.14fr/);
  assert.match(css, /\.revenueEquation \{ display: grid; grid-template-columns: repeat\(4, 1fr\)/);
  assert.match(css, /\.gapGrid \{ grid-template-columns: repeat\(4, 1fr\)/);
  assert.match(css, /\.productGatePage \{[\s\S]*?min-height: calc\(100svh - 24px\)/);
  assert.match(css, /\.productGateMatrix \{[^}]*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/);
  assert.match(css, /@media \(max-width: 760px\) \{[\s\S]*?\.productGateMatrix \{ grid-template-columns: 1fr/);
  assert.match(css, /\.roadmapPage \{[\s\S]*?min-height: calc\(100svh - 24px\)/);
  assert.match(css, /\.roadmapEvolution \{[^}]*grid-template-columns: 292px 32px minmax\(0, 1fr\) 32px 292px/);
  assert.match(css, /@media \(max-width: 760px\) \{[\s\S]*?\.roadmapEngineInputs \{ grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/);
  assert.doesNotMatch(css, /\.marketAccessRequirement|\.marketAccessMetric|\.marketAccessPlan|\.resellRoute|\.resellPrinciples/);
  assert.match(css, /\.solutionPageBody \{ display: grid; grid-template-columns: 1fr/);
  assert.match(css, /\.brandSolutionBody \{[^}]*grid-template-columns: minmax\(340px, \.72fr\) minmax\(0, 1\.28fr\)/);
  assert.match(css, /\.brandOriginalFlow \{[^}]*grid-template-columns: minmax\(175px, \.82fr\)/);
  assert.match(css, /\.brandDemoCompactGrid \{[^}]*grid-template-columns: repeat\(4, minmax\(0, 1fr\)\)/);
  assert.match(css, /#language-mode:checked ~ \.solutions \.brandSolutionPage \.langEn/);
  assert.match(css, /\.performanceDemoGallery \{ grid-template-columns: repeat\(4, minmax\(0, 1fr\)\)/);
  assert.match(css, /\.displaySolutionBody \{[^}]*grid-template-columns: 1fr;[^}]*grid-template-rows: 306px minmax\(0, 1fr\)/);
  assert.match(css, /\.displayDemoGalleryGrid \{[^}]*grid-template-columns: 1\.6fr 1\.78fr 3fr/);
  assert.match(css, /\.displayDemoTile img \{[^}]*object-fit: contain/);
  assert.match(css, /\.playableFactoryGrid \{[^}]*grid-template-columns: minmax\(190px, \.68fr\) 28px minmax\(500px, 1\.58fr\) 28px minmax\(310px, 1fr\)/);
  assert.match(css, /\.playableDemoGrid \{[^}]*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/);
  assert.match(css, /\.segmentCell strong \{[^}]*font-size: 16px/);
  assert.match(css, /\.segmentCell span \{[^}]*font-size: 12px/);
  assert.match(css, /\.dimensionCell b \{ font-size: 14px/);
  assert.match(css, /\.sampleMedia > video \{[^}]*object-fit: cover/);
  assert.match(css, /\.displayBoard \{ grid-template-columns: 1fr/);
  assert.match(css, /\.coverPage \{ min-height: calc\(100svh - 76px\)/);
  assert.match(css, /\.coverPageInner \{ min-height: calc\(100svh - 76px\); display: flex/);
  assert.match(css, /@media \(max-width: 760px\)[\s\S]*\.coverPage h1/);

  const page = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  assert.match(page, /className="marketFlowTitle"/);
  assert.match(page, /AI 降低视频生产成本[\s\S]*供给规模化[\s\S]*预算迁移/);
  assert.match(css, /\.marketFlowShell \{/);
  assert.match(css, /\.marketFlowFigure \{/);
  assert.match(css, /\.marketFlowAiBand \{/);
  assert.match(css, /\.marketFlowMobile \{/);
  assert.match(css, /\.flowSegments,\s*\.flowOutcome \{ opacity: 0/);
  assert.match(css, /\.segmentControl:checked ~ \.marketFlowSvg \.flowSegments/);
  assert.match(css, /\.segmentControl:checked ~ \.marketFlowMobile \.mobileSegmentDetails \{ display: block/);
});
